#!/usr/bin/env python3
"""
Import an official BioMar policy PDF into an editable .docx source that the
formatter can re-render faithfully.

Uses PyMuPDF to read the real page structure (text blocks with font sizes,
reading order, and tables) and rebuilds a clean .docx:

* the cover page and the running header/footer band are dropped (the formatter
  draws its own);
* the trailing version / owner-approver card is dropped (regenerated by the
  formatter), whether the PDF stores it as text or as a table;
* a leading "Contents" table-of-contents is dropped;
* headings are levelled by font size, bullets are detected, and real tables are
  rebuilt as Word tables.

    python import_pdf.py INPUT.pdf -o OUTPUT.docx

Render any PDF (original or generated) to PNGs for visual QA:

    python import_pdf.py --render INPUT.pdf --out-dir /tmp/qa [--dpi 110]
"""
import argparse
import re
from collections import Counter
from io import BytesIO

import fitz  # PyMuPDF
from docx import Document
from docx.shared import Pt as DocxPt

CTRL = re.compile(r"[\x00-\x08\x0b\x0c\x0e-\x1f]")
BOILER = ("Kalkværksvej", "www.biomar.com")
VCARD_MARK = ("Version history", "Owner and approver", "Owner and Approver")


def _clean(s):
    return CTRL.sub("", s or "")


def _is_vcard_table(rows):
    flat = " ".join((c or "") for r in rows for c in r)
    return ("Approval date" in flat) or ("Owner" in flat and "Approver" in flat)


def extract_items(pdf):
    """Return ordered [(kind, payload)] across content pages.
    kind 'block' -> (text, size, bold, x0); kind 'table' -> rows."""
    doc = fitz.open(pdf)
    items = []
    for pno in range(doc.page_count):
        if pno == 0:                      # cover
            continue
        page = doc[pno]
        H = page.rect.height
        try:
            tables = page.find_tables().tables
        except Exception:
            tables = []
        trects = [fitz.Rect(t.bbox) for t in tables]

        page_items = []
        for t in tables:
            try:
                rows = t.extract()
            except Exception:
                rows = None
            if rows:
                page_items.append((fitz.Rect(t.bbox).y0, "table", rows))

        for b in page.get_text("dict")["blocks"]:
            if b.get("type") != 0:
                continue
            rb = fitz.Rect(b["bbox"])
            # inside a detected table -> handled as table
            if any(rb.intersects(tr) and (rb & tr).get_area() > 0.5 * rb.get_area() for tr in trects):
                continue
            if rb.y0 < H * 0.085 or rb.y1 > H * 0.94:   # header/footer band
                continue
            parts, sizes, bold = [], [], False
            for ln in b["lines"]:
                for sp in ln["spans"]:
                    parts.append(sp["text"])
                    sizes.append(round(sp["size"], 1))
                    if (sp["flags"] & 16) or any(k in sp["font"] for k in ("Bold", "Demi", "Semibold", "Black")):
                        bold = True
                parts.append("\n")
            s = "".join(parts).strip()
            if not s or s == "BioMar Group" or any(b0 in s for b0 in BOILER):
                continue
            size = Counter(sizes).most_common(1)[0][0] if sizes else 11.0
            page_items.append((rb.y0, "block", (s, size, bold, rb.x0)))

        # content images (skip the logo / header / footer / full-page artwork)
        for im in page.get_image_info(xrefs=True):
            bb = fitz.Rect(im["bbox"])
            if bb.y0 < H * 0.10 or bb.y1 > H * 0.93:
                continue
            if bb.width < 42 or bb.height < 30:
                continue
            if bb.get_area() > 0.72 * page.rect.get_area():
                continue
            xref = im.get("xref", 0)
            if not xref:
                continue
            try:
                pix = fitz.Pixmap(doc, xref)
                if pix.n - pix.alpha >= 4:            # CMYK/other -> RGB
                    pix = fitz.Pixmap(fitz.csRGB, pix)
                png = pix.tobytes("png")
            except Exception:
                continue
            page_items.append((bb.y0, "image", (png, bb.width, bb.height)))

        page_items.sort(key=lambda it: it[0])
        items.extend((k, p) for _, k, p in page_items)
    return items


def build_docx(pdf, out):
    items = extract_items(pdf)

    # Drop the version/owner-approver card and everything after it.
    cut = len(items)
    for i, (k, p) in enumerate(items):
        if (k == "block" and (any(m in p[0] for m in VCARD_MARK) or re.match(r"\s*Owner\s*:", p[0]))) \
                or (k == "table" and _is_vcard_table(p)):
            cut = min(cut, i)
    items = items[:cut]

    body_c = Counter(p[1] for k, p in items if k == "block" and len(p[0]) > 60)
    body = body_c.most_common(1)[0][0] if body_c else 11.0
    head_sizes = sorted({p[1] for k, p in items if k == "block" and p[1] > body + 0.4}, reverse=True)
    h1 = head_sizes[0] if head_sizes else None

    doc = Document()
    skip_toc = False
    last_para = None           # last body paragraph, for merging split continuations
    for k, p in items:
        if k == "image":
            png, w, _h = p
            try:
                doc.add_picture(BytesIO(png), width=DocxPt(min(w, 470)))
            except Exception:
                pass
            last_para = None
            continue
        if k == "table":
            last_para = None
            rows = [r for r in p if any((c or "").strip() for c in r)]
            if not rows:
                continue
            cols = max(len(r) for r in rows)
            tbl = doc.add_table(rows=0, cols=cols)
            try:
                tbl.style = "Table Grid"
            except Exception:
                pass
            for r in rows:
                cells = tbl.add_row().cells
                for j in range(cols):
                    cells[j].text = _clean((r[j] or "").strip()) if j < len(r) else ""
            doc.add_paragraph("")
            continue

        s, size, bold, _x0 = p
        s = _clean(re.sub(r"[ \t]*\n[ \t]*", " ", s).strip())
        s = re.sub(r" {2,}", " ", s)
        if not s:
            continue
        is_head = (size in head_sizes) or (bold and size > body + 0.3)

        if is_head and re.match(r"^contents?$", s, re.I):
            skip_toc = True
            last_para = None
            continue
        if skip_toc:
            if len(s) > 90 or s.endswith("."):
                skip_toc = False           # real body resumed
            else:
                continue

        if is_head:
            level = 1 if (h1 and size >= h1 - 0.1) else 2
            doc.add_heading(s, level=level)
            last_para = None
        elif s[:1] in "••-▪◦":
            for line in s.split("\n"):
                item = re.sub(r"^[\s••\-▪◦]+", "", line).strip()
                if item:
                    doc.add_paragraph(item, style="List Bullet")
            last_para = None
        else:
            # Merge a block that is the continuation of the previous paragraph
            # (previous didn't end a sentence and this one starts lower-case).
            if last_para is not None and s[:1].islower() and not re.search(r"[.:;!?»\")]\s*$", last_para.text):
                last_para.text = last_para.text + " " + s
            else:
                last_para = doc.add_paragraph(s)
    doc.save(out)


def render(pdf, out_dir, dpi):
    import os
    os.makedirs(out_dir, exist_ok=True)
    doc = fitz.open(pdf)
    base = os.path.splitext(os.path.basename(pdf))[0]
    for pno in range(doc.page_count):
        doc[pno].get_pixmap(dpi=dpi).save(os.path.join(out_dir, f"{base}_p{pno + 1}.png"))
    print(f"rendered {doc.page_count} pages -> {out_dir}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("input")
    ap.add_argument("-o", "--output")
    ap.add_argument("--render", action="store_true", help="render to PNGs instead of converting")
    ap.add_argument("--out-dir", default="/tmp/qa")
    ap.add_argument("--dpi", type=int, default=110)
    a = ap.parse_args()
    if a.render:
        render(a.input, a.out_dir, a.dpi)
    else:
        build_docx(a.input, a.output)
        print("wrote", a.output)


if __name__ == "__main__":
    main()
